GET http://localhost:8080/api/crash/list
Accept: application/json

###

POST http://localhost:8080/public/crash/add
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="file.txt"

< ../../src/test/resources/UE4CC-Windows-A10B637D4D1A6B31FAFC3A84ACE30E60_0000.zip
--WebAppBoundary--
Content-Disposition: form-data; name="description";

There was a crash you fool!
--WebAppBoundary--
Content-Disposition: form-data; name="version";

Development1234567
--WebAppBoundary--

###

POST http://localhost:8080/api/crash/1/diagnostics
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="file.txt"

< ../../src/test/resources/Diagnostics.txt
--WebAppBoundary--

###

